export default {
  DAYS: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  FORMAT: {
    DATE_WITH_MONTH: 'DD MMMM YYYY',
    DATE: 'DD-MMM-YYYY',
    MONTH: 'MMMM YYYY'
  },
  GO_TO_TODAY: 'GO_TO_TODAY',
  HABITS: 'HABITS',
  HIDE_INTRO_SCREEN: 'HIDE_INTRO_SCREEN',
  SELECTED_DATE: 'SELECTED_DATE',
  SELECTED_HABIT: 'SELECTED_HABIT',
  TOGGLE_ADD_MODAL: 'TOGGLE_ADD_MODAL',
  TOGGLE_ALL_HABITS_MODAL: 'TOGGLE_ALL_HABITS_MODAL'
}
