export default {
  DAYS: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  FORMAT: {
    DATE: 'DD-MMM-YYYY',
    MONTH: 'MMMM YYYY',
    DATE_WITH_MONTH: 'DD MMMM YYYY'
  },
  HABITS: 'HABITS',
  SELECTED_HABIT: 'SELECTED_HABIT',
  TOGGLE_ALL_HABITS_MODAL: 'TOGGLE_ALL_HABITS_MODAL',
  SELECTED_DATE: 'SELECTED_DATE',
  TOGGLE_ADD_MODAL: 'TOGGLE_ADD_MODAL'
}
